version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image:
      stats-server
    container_name:
      stats-server
    ports:
      - "9091:9091"
    depends_on:
      ewm-db:
        condition: service_started
      stats-dtos:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
    networks:
      - net

  stats-dtos:
    build: ./stats-service/stats-dtos
    image:
      stats-dtos
    container_name:
      stats-dtos

  stats-client:
    build: ./stats-service/stats-client
    image:
      stats-client
    container_name:
      stats-client
    ports:
      - "9090:9090"
    depends_on:
      stats-dtos:
        condition: service_started
      stats-server:
        condition: service_started
    environment:
      - EWM_STAT_SERVER_URL=http://stats-server:9091
    networks:
      - net

  ewm-service:
    build: ./main-service
    image:
      ewm-service
    container_name:
      ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_started
      stats-client:
        condition: service_started
    environment:
      - EWM_CLIENT_URL=http://stats-client:9090

  ewm-db:
    image:
      postgres:14-alpine
    container_name:
      ewm-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    networks:
      - net


networks:
  net:
    driver: "bridge"