version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image:
      stats-server
    container_name:
      stats-server
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
    networks:
      - net

  stats-client:
    build: ./stats-service/stats-client
    image:
      stats-client
    container_name:
      stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - EWM_STAT_SERVER_URL=http://stats-server:9091
    networks:
      - net

  ewm-service:
    build: ./main-service
    image:
      ewm-service
    container_name:
      ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-client
    environment:
      - EWM_CLIENT_URL=http://stats-client:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
    networks:
      - net

  stats-db:
    image:
      postgres:14-alpine
    container_name:
      stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    networks:
      - net

  ewm-db:
    image:
      postgres:14-alpine
    container_name:
      ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    networks:
      - net


networks:
  net:
    driver: "bridge"